name: 发布到Github Page

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  # Build for wasm
  build:
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      contents: read

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.toml') }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: install trunk
        run: |
          cargo install trunk

      - name: Build
        run: |
          trunk build --release
      
      # - name: Package as a zip
      #   working-directory: ./dist
      #   run: |
      #     tar czf target.tar.gz --directory=path/to/directory .
      #     zip --recurse-paths ../github-pages.zip .

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './dist'
      # - name: Upload binaries to artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: github-pages.zip
      #     name: github-pages
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build



    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps: